version: '3.7'

services:

  ghar_frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/opt/app'
      - '/docker-volumes/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  

  ghar_api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/opt/api'
      - '/docker-volumes/api/node_modules'
    ports:
      - 5000:5000
      - 6379:6379
    environment:
      - CHOKIDAR_USEPOLLING=true  